teams:
  - name: staff
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
    visibility: public
  - name: bevel-admins
    maintainers:
      - sownak
  - name: bevel-committers
    maintainers:
      - arsulegai
      - suvajit-sarkar
    members:
      - adityajoshi12
      - jagpreetsinghsasan
      - petermetz
      - sownak
      - weihong-ou
      - alvaropicazo
  - name: bevel-contributors
    maintainers:
      - petermetz
      - sownak
    members:
      - adityajoshi12
      - alvaropicazo
      - arsulegai
      - dviejokfs
      - jagpreetsinghsasan
      - mgCepeda
      - ravikiranjanjanam
      - saikumarbommakanti
      - saurabhkumarkardam
      - suvajit-sarkar
      - weihong-ou
  - name: bevel-operator-fabric-admins
    maintainers:
      - dviejokfs
  - name: bevel-operator-fabric-committers
    maintainers:
      - dviejokfs
    members:
      - adityajoshi12
  - name: bevel-samples-admins
    maintainers:
      - suvajit-sarkar
  - name: bevel-triage
    maintainers:
      - jonathan-m-hamilton
    members:
      - alvaropicazo
      - saikumarbommakanti
      - saurabhkumarkardam
      - suvajit-sarkar
      - tkuhrt
repositories:
  - name: governance
    teams:
      staff: maintain
  - name: bevel
    teams:
      bevel-admins: admin
      bevel-committers: maintain
      bevel-contributors: read
      bevel-operator-fabric-admins: read
      bevel-operator-fabric-committers: read
      bevel-samples-admins: admin
      bevel-triage: triage
    visibility: public
  - name: bevel-operator-fabric
    teams:
      bevel-admins: admin
      bevel-committers: maintain
      bevel-contributors: read
      bevel-operator-fabric-admins: admin
      bevel-operator-fabric-committers: maintain
      bevel-samples-admins: admin
      bevel-triage: triage
    visibility: public
  - name: bevel-samples
    teams:
      bevel-admins: admin
      bevel-committers: write
      bevel-contributors: read
      bevel-operator-fabric-admins: read
      bevel-operator-fabric-committers: read
      bevel-samples-admins: admin
      bevel-triage: triage
    visibility: public
